---
title: "Populist Parties and Quality of Democracy"
author: "Lauth, Hans-Joachim und Schlenkrich, Oliver"
date: "05.06.2019"
output: 
  beamer_presentation:
    fonttheme: "professionalfonts"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

```

## Consequences of Populist Rule?

- Declining Quality of Democracy?


## Populist Parties per Country: Seat Share

```{r pressure, message=FALSE, warning=FALSE}

populist_yearly %>% 
  filter(populist == 1, year > 2000)  %>% 
  group_by(country_name, party_name_short, party_id) %>% 
  summarise(left_right = mean(left_right, na.rm=T),
            state_market = mean(state_market, na.rm=T),
            perc_seats = mean(perc_seats, na.rm=T),
  ) %>% 
  ggplot(aes(y=left_right, x=state_market)) +
  geom_point(aes(size=perc_seats)) + 
  theme_bw() +
  scale_size_continuous(name="Seats Share (%)")  +
  geom_label_repel(aes(label=party_name_short), size = 3) +
  facet_wrap(country_name ~ .) +
  ggtitle("Populist Parties per country (Since 2000; Seat Share in Parliament)")

```

