# Packages
library(stringr)
library(gtools)
library(dplyr)
library(data.table)
library(ggplot2)
library(gridExtra)
library(forcats)
library(lmtest)
library(plm)
library(panelAR)
library(mclust)
library(fpc)
library(zoo)
library(imputeTS)
library(scales)
library(bit64)
library(psych)
library(effects)
library(corrplot)
library(ggrepel)
library(tidyr)
library(boot)
library(knitr)
library(rmarkdown)
library(stargazer)
library(onehot)
library(car)
library(fastDummies)
library(psych)
library(pixiedust)
library(broom.mixed)


library(brms)
options(mc.cores = parallel::detectCores())


